[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Direct.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🍇 数据采集"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Data.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-game-accelerator-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🗽 美国分流"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🗨️ ChatGPT"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/OpenAI.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🗨️ ChatGPT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🗨️ ChatGPT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "📱 TikTok"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🐧 Tencent"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🐧 Tencent"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TencentVideo/TencentVideo_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🐧 Tencent"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tencent-games.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🐧 Tencent"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tencent.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🐧 Tencent"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Tencent/Tencent_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "📺 哔哩哔哩"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "📺 哔哩哔哩"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "📺 哔哩哔哩"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/biliintl.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "📱 抖音集团"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "📱 抖音集团"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bytedance.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "Ⓜ️ Meta"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/facebook.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "Ⓜ️ Meta"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "📽️ Netflix"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🕊️ xAI"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/x.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🍎 Apple"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🎮 Steam"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Teams/Teams_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "📚 Ms.Copilot"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bing.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "📚 Ms.Copilot"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Ms.Copilot.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "⛅ OneDrive"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "⛅ OneDrive"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/OneDrive.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/azure.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "📟 Xbox"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/xbox.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "👬🏻 GitHub"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "💾 Microsoft"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gog.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🗽 美国分流"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/blizzard.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🗽 美国分流"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ubisoft.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🗽 美国分流"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ea.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🗽 美国分流"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🛁 YouTube"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "💻 Google"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "💸 PayPal"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "⛺ Adobe"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/adobe.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonCN/AmazonCN_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/amazon.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Amazon/Amazon_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cloudflare-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cloudflare.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloudflare/Cloudflare_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "♾️ 无限流量"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tracker.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "♾️ 无限流量"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-public-tracker.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🍙 日本高速"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/niconico.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🍙 日本高速"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/dmm.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-dev-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-dev.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🌈 香港高速"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Hongkong.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🍙 日本高速"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Japan.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🐸 台湾分流"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Taiwan.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🦁 新加坡分流"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Singapore.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🗽 美国分流"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/America.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🗽 美国分流"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Los_Angeles.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/Proxy.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/xiaohongshu.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/alibaba.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/Alibaba_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/sina.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/baidu.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/jd.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/hupu.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Youku/Youku_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iQIYI/iQIYI_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoMi/XiaoMi_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-scholar-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-scholar-!cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cnbeta.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-media-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-social-media-cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🗽 美国分流"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-media.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🌍 国外流媒体"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🌍 国外流媒体"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "🌍 国外流媒体"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloud/CloudCN/CloudCN_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "☁️ 国际Cloud"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloud/CloudGlobal/CloudGlobal_Classical_No_Resolve.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "🌠 节点选择"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml"
type = "clash-domain"
interval = 21600

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/angwz/Clash_Angrules/main/Rules/China.yaml"
type = "clash-classic"
interval = 21600

[[rulesets]]
group = "Ⓜ️ Meta"
ruleset = "[]GEOIP,FACEBOOK,no-resolve"

[[rulesets]]
group = "📽️ Netflix"
ruleset = "[]GEOIP,NETFLIX,no-resolve"

[[rulesets]]
group = "🕊️ xAI"
ruleset = "[]GEOIP,TWITTER,no-resolve"

[[rulesets]]
group = "💻 Google"
ruleset = "[]GEOIP,GOOGLE,no-resolve"

[[rulesets]]
group = "🌠 节点选择"
ruleset = "[]GEOIP,CLOUDFLARE,no-resolve"

[[rulesets]]
group = "🌠 节点选择"
ruleset = "[]GEOIP,TELEGRAM,no-resolve"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,FASTLY,no-resolve"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CLOUDFRONT,no-resolve"

[[rulesets]]
group = "🌈 香港高速"
ruleset = "[]GEOIP,HK,no-resolve"

[[rulesets]]
group = "🍙 日本高速"
ruleset = "[]GEOIP,JP,no-resolve"

[[rulesets]]
group = "🐸 台湾分流"
ruleset = "[]GEOIP,TW,no-resolve"

[[rulesets]]
group = "🦁 新加坡分流"
ruleset = "[]GEOIP,SG,no-resolve"

[[rulesets]]
group = "🗽 美国分流"
ruleset = "[]GEOIP,US,no-resolve"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "🐳 漏网の鱼"
ruleset = "[]MATCH"
