name: Clear Release Branch and Releases

on:
  workflow_dispatch: # 手动触发

permissions:
  contents: write
  actions: write

jobs:
  clear_release_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout release branch
      run: |
        git fetch origin
        git checkout release

    - name: Remove all files
      run: |
        git rm -rf .
        git clean -fdx

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m 'Clear release branch'
        git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/angwz/DomainRouter.git release

    - name: List all releases
      id: list_releases
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/:owner/:repo/releases
        owner: angwz
        repo: DomainRouter
        mediaType: '{"format":"json"}'
      env:
        GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}

    - name: Delete all releases
      if: steps.list_releases.outputs.status == 200
      run: |
        releases=$(echo '${{ steps.list_releases.outputs.data }}' | jq -r '.[].id')
        for release_id in $releases; do
          curl -X DELETE \
          -H "Authorization: token ${{ secrets.FULL_ACCESS_TOKEN }}" \
          "https://api.github.com/repos/angwz/DomainRouter/releases/$release_id"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}
