name: Trigger Updates

on:
  push:
    branches:
      - main
    paths:
      - my.wei

jobs:
  update_domain_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger update_domain_rules workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update_domain_rules.yml
          token: ${{ secrets.FULL_ACCESS_TOKEN }}

  wait_and_trigger_update_rulesets:
    runs-on: ubuntu-latest
    needs: update_domain_rules

    steps:
      - name: Wait for 30 seconds
        run: sleep 30

      - name: Trigger update_rulesets_toml workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update_rulesets_toml.yml
          token: ${{ secrets.FULL_ACCESS_TOKEN }}
