name: Trigger Updates

on:
  push:
    branches:
      - main
    paths:
      - my.wei

jobs:
  update_domain_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger update_domain_rules workflow
        id: trigger_domain_rules
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update_domain_rules.yml
          token: ${{ secrets.FULL_ACCESS_TOKEN }}

      - name: Wait for update_domain_rules to complete
        run: |
          sleep 30
          CHECK_INTERVAL=10
          while [ "$(gh run list --workflow=update_domain_rules.yml --branch=main --status=in_progress --json conclusion --jq '.[0].conclusion')" == "null" ]; do
            echo "Waiting for update_domain_rules workflow to complete..."
            sleep $CHECK_INTERVAL
          done
        env:
          GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}

      - name: Wait additional 30 seconds
        run: sleep 30

      - name: Trigger update_rulesets_toml workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update_rulesets_toml.yml
          token: ${{ secrets.FULL_ACCESS_TOKEN }}
