name: Trigger Updates

on:
  push:
    branches:
      - main
    paths:
      - my.wei
  workflow_dispatch: # 支持手动触发

jobs:
  update_domain_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Trigger update_domain_rules workflow
        id: trigger_domain_rules
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'update_domain_rules.yml',
              ref: 'main'
            });
            return response.data;

      - name: Wait for update_domain_rules to complete
        run: |
          CHECK_INTERVAL=30
          while true; do
            STATUS=$(gh run list --workflow=update_domain_rules.yml --branch=main --limit 1 --json status --jq '.[0].status')
            echo "Current status: $STATUS"
            if [ "$STATUS" == "completed" ]; then
              echo "update_domain_rules workflow has completed."
              break
            fi
            echo "Waiting for update_domain_rules workflow to complete..."
            sleep $CHECK_INTERVAL
          done
        env:
          GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}

      - name: Wait additional 30 seconds
        run: sleep 30

      - name: Trigger update_rulesets_toml workflow
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'update_rulesets_toml.yml',
              ref: 'main'
            });
            return response.data;
        env:
          GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}
