name: Update CN Conf

on:
  schedule:
    - cron: '0 16 * * 0' # 北京时间周一00点00分（UTC时间周日16点00分）
  workflow_dispatch: # 手动触发

permissions:
  contents: write

jobs:
  update_cn_conf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyyaml requests

    - name: Run script
      run: |
        python script/domain_convert_dnsmasq.conf.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add dnsmasq/china-domains.conf
        git commit -m 'Update china-domains.conf'
        git push https://x-access-token:${{ secrets.TOKEN }}@github.com/angwz/DomainRouter.git
